{
 "title": "AA",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Application Assurance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Packet Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "application_assurance_group_status_summary_statistics_packet_rate_current",
       "legendFormat": "Packet Rate"
      }
     ]
    },
    {
     "title": "Traffic Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "application_assurance_group_status_summary_statistics_traffic_rate_current*1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Flow Setup Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "application_assurance_group_status_summary_statistics_flow_setup_rate_current",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffic Identification",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "deriv(application_assurance_group_partition_application_statistics_net_to_sub_admitted_octets[300s])*8",
       "legendFormat": "{{application_application_name}}"
      },
      {
       "expr": "sum(deriv(application_assurance_group_partition_application_statistics_net_to_sub_admitted_octets[300s])*8)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of Subscribers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "application_assurance_group_status_summary_statistics_active_subscribers_current",
       "legendFormat": "Subscribers"
      }
     ]
    }
   ]
  },
  {
   "title": "Routing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Routes Default Instance, $source",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
       "legendFormat": "IPv4"
      },
      {
       "expr": "network_instance_route_table_ipv6_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
       "legendFormat": "IPv6"
      },
      {
       "expr": "router_bgp_statistics_routes_per_family_ipv4_remote_routes{source=\"$source\"}",
       "legendFormat": "IPv4"
      },
      {
       "expr": "router_bgp_statistics_routes_per_family_ipv6_remote_routes{source=\"$source\"}",
       "legendFormat": "IPv6"
      },
      {
       "expr": "router_bgp_statistics_routes_per_family_vpn_ipv4_remote_routes{source=\"$source\"}",
       "legendFormat": "VPN-IPv4"
      },
      {
       "expr": "router_bgp_statistics_routes_per_family_vpn_ipv6_remote_routes{source=\"$source\"}",
       "legendFormat": "VPN-IPv6"
      }
     ]
    },
    {
     "title": "BGP Peers: $source",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 3, "x": 8, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "router_bgp_convergence_family_up_peers{source=\"$source\",family_family_type=\"ipv6\"}",
       "legendFormat": "UP Peers"
      }
     ]
    },
    {
     "title": "MAC Table Instance: $network_instance, $source",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 11, "y": 65 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "network_instance_bridge_table_statistics_total_entries{network_instance_name=\"$network_instance\",source=\"$source\"}",
       "legendFormat": "MAC Entries"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Ingress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * 100) * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "In: $source -> {{interface_name}}"
      }
     ]
    },
    {
     "title": "Traffic Egress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "Out: $source -> {{interface_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Aggregate Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Aggregate Rate -> $source ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "In: $source -> {{interface_name}}"
    }
   ]
  },
  {
   "title": "cVSR",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 14, "w": 9, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "UP0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "UP1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "UP2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/7|1/1/8|1/1/9\"}[$__rate_interval])*8)",
     "legendFormat": "UP3"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN3"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{source=\"$source\",subscription_name=\"sros-system-performance\"}",
     "legendFormat": "Router: {{source}}"
    },
    {
     "expr": "platform_control_cpu_total_average_15{source=\"$source\"}",
     "legendFormat": "Router: {{source}}"
    }
   ]
  },
  {
   "title": "CPU Utilization: $source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_summary_busiest_core_utilization_cpu_usage{source=\"$source\"}",
     "legendFormat": "Busiest Core Utilization"
    },
    {
     "expr": "system_cpu_isa_cpu_usage{source=\"$source\"}",
     "legendFormat": "ISA CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use{source=\"$source\"}/( system_memory_pools_summary_total_in_use{source=\"$source\"} + system_memory_pools_summary_available_memory{source=\"$source\"})*100",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$source\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}