{
 "title": "AnySec Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "AnySec_EndPoints", "query": { "query": "label_values(source)" } },
   {
    "name": "Encryption_Group",
    "query": {
     "query": "query_result(gnmic_sros_anysec_peer_encryption_label)"
    }
   },
   { "name": "MacSec_EndPoints", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  { "title": "AnySec Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Link Bandwidth",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "gnmic_sros_port_oper_state_oper_state",
     "legendFormat": "{{source}}:{{port_port_id}}"
    },
    {
     "expr": "rate(gnmic_sros_port_stats_in_octets[30s])*8",
     "legendFormat": "{{source}}:{{port_port_id}}:in"
    },
    {
     "expr": "rate(gnmic_sros_port_stats_out_octets[30s])*8",
     "legendFormat": "{{source}}:{{port_port_id}}:out"
    },
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_encrypted{source=\"pe1:57400\"}[30s])*8)",
     "legendFormat": "anysec_encrypted_packets:pe1:57400:out"
    },
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_encrypted{source=\"pe2:57400\"}[30s])*8)",
     "legendFormat": "anysec_encrypted_packets:pe2:57400:out"
    },
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_decrypted{source=\"pe1:57400\"}[30s])*8)",
     "legendFormat": "anysec_decrypted_packets:pe1:57400:in"
    },
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_decrypted{source=\"pe2:57400\"}[30s])*8)",
     "legendFormat": "anysec_decrypted_packets:pe2:57400:in"
    },
    {
     "expr": "rate(gnmic_sros_macsec_if_stats_octets_decrypted[30s])*8",
     "legendFormat": "macsec_decrypted_packets:{{source}}:{{port_port_id}}:in"
    },
    {
     "expr": "rate(gnmic_sros_macsec_if_stats_octets_encrypted[30s])*8",
     "legendFormat": "macsec_encrypted_packets:{{source}}:{{port_port_id}}:out"
    },
    {
     "expr": "gnmic_sros_macsec_config_admin_state",
     "legendFormat": "macsec:{{source}}:{{connectivity_association_ca_name}}"
    },
    {
     "expr": "gnmic_sros_anysec_encryption_group_admin_state{encryption_group_group_name=\"$Encryption_Group\", source=\"pe1:57400\",peer_peer_ip_address=~\"10\\\\.0\\\\.0\\\\.2|10\\\\.0\\\\.0\\\\.21|10\\\\.0\\\\.0\\\\.22\"}",
     "legendFormat": "any_sec:pe1:57400"
    },
    {
     "expr": "gnmic_sros_anysec_encryption_group_admin_state{encryption_group_group_name=\"$Encryption_Group\", source=\"pe2:57400\",peer_peer_ip_address=~\"10\\\\.0\\\\.0\\\\.1|10\\\\.0\\\\.0\\\\.11|10\\\\.0\\\\.0\\\\.12\"}",
     "legendFormat": "any_sec:pe2:57400"
    }
   ]
  },
  { "title": "$AnySec_EndPoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Encryption Label",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_peer_encryption_label{source=\"$AnySec_EndPoints\",encryption_group_group_name=\"$Encryption_Group\"}",
     "legendFormat": "{{peer_peer_ip_address}}"
    }
   ]
  },
  {
   "title": "AnySec Peer Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_peer_oper_state{source=\"$AnySec_EndPoints\",encryption_group_group_name=\"$Encryption_Group\"}",
     "legendFormat": "{{peer_peer_ip_address}}"
    }
   ]
  },
  {
   "title": "Security Termination Policy",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_sec_termination_policy_terminating_label{source=\"$AnySec_EndPoints\"}",
     "legendFormat": "{{security_termination_policy_policy_name}}"
    }
   ]
  },
  {
   "title": "ISIS ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_encryption_group_igp_instance_id{source=\"$AnySec_EndPoints\",encryption_group_group_name=\"$Encryption_Group\"}",
     "legendFormat": "{{encryption_group_group_name}}"
    }
   ]
  },
  {
   "title": "AnySec Encrypted Packets Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_encrypted{source=\"$AnySec_EndPoints\"}[30s])*8)",
     "legendFormat": "Encrypted Packets"
    }
   ]
  },
  {
   "title": "AnySec Decrypted Packets Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(gnmic_sros_anysec_peer_octets_decrypted{source=\"$AnySec_EndPoints\"}[30s])*8)",
     "legendFormat": "Decrypted Packets"
    }
   ]
  },
  {
   "title": "Tunnel ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_peer_tunnel_id{source=\"$AnySec_EndPoints\",encryption_group_group_name=\"$Encryption_Group\"}",
     "legendFormat": "{{encryption_group_group_name}}"
    }
   ]
  },
  {
   "title": "MKA UDP Port",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_mka_over_ip_mka_udp_port{source=\"$AnySec_EndPoints\"}",
     "legendFormat": "OK Packets "
    }
   ]
  },
  {
   "title": "Delayed Packets Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_anysec_peer_delayed_packets{source=\"$AnySec_EndPoints\",encryption_group_group_name=\"$Encryption_Group\"}",
     "legendFormat": "Delayed Packets"
    }
   ]
  },
  { "title": "$MacSec_EndPoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "MacSec_EndPoints" },
  {
   "title": "MacSec Live Peer Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_macsec_if_stats_new_live_peer{source=\"$MacSec_EndPoints\"}",
     "legendFormat": "{{port_port_id}}"
    }
   ]
  },
  {
   "title": "MacSec OK Packets Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_macsec_if_stats_ok_packets{source=\"$MacSec_EndPoints\"}",
     "legendFormat": "{{source}}:{{port_port_id}}"
    }
   ]
  },
  {
   "title": "MacSec Connectivity Association",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_macsec_connectivity_association_psk_id{source=\"$MacSec_EndPoints\"}",
     "legendFormat": "{{connectivity_association_ca_name}}"
    }
   ]
  },
  {
   "title": "MacSec Encrypted Packets Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_macsec_if_stats_octets_encrypted{source=\"$MacSec_EndPoints\"}[30s])*8",
     "legendFormat": "Encrypted Packets"
    }
   ]
  },
  {
   "title": "MacSec Decrypted Packets Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_macsec_if_stats_octets_decrypted{source=\"$MacSec_EndPoints\"}[30s])*8",
     "legendFormat": "Decrypted Packets"
    }
   ]
  },
  {
   "title": "MacSec Removed Peers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_macsec_if_stats_peers_removed{source=\"$MacSec_EndPoints\"}",
     "legendFormat": "{{port_port_id}}"
    }
   ]
  },
  {
   "title": "MacSec Delayed Packets Statistics",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_macsec_if_stats_delayed_packets{source=\"$MacSec_EndPoints\"}",
     "legendFormat": "{{source}}:{{port_port_id}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "VPRN Service ",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "gnmic_sros_vprn_instance_oper_state_oper_state",
     "legendFormat": "{{source}}:{{vprn_service_name}}"
    }
   ]
  },
  {
   "title": "VPLS Service ",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 54 },
   "targets": [
    {
     "expr": "gnmic_sros_vpls_instance_oper_state_oper_state",
     "legendFormat": "{{source}}:{{vpls_service_name}}"
    }
   ]
  },
  {
   "title": "ePipe Service ",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "gnmic_sros_epipe_instance_oper_state_oper_state",
     "legendFormat": "{{source}}:{{epipe_service_name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_sros_port_stats_in_octets{source=~\"$AnySec_EndPoints|$MacSec_EndPoints\"}[30s])*8",
     "legendFormat": "{{port_port_id}}:IN"
    },
    {
     "expr": "rate(gnmic_sros_port_stats_out_octets{source=~\"$AnySec_EndPoints|$MacSec_EndPoints\"}[30s])*8",
     "legendFormat": "{{port_port_id}}:OUT"
    }
   ]
  }
 ]
}