{
 "title": "BNG",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "BNG User Plane Key Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vFP Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NIC_key3{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key3{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key3{job=\"$source\"}",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "title": "vFP vCPUs -> $source",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NIC_key1{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key1{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key1{job=\"$source\"}",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "title": "cVSR",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 19, "w": 11, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "UP0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "UP1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "UP2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/7|1/1/8|1/1/9\"}[$__rate_interval])*8)",
     "legendFormat": "UP3"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/7|1/1/8|1/1/9\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN3"
    }
   ]
  },
  {
   "title": "vFP Average Utilization -> $source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "NIC_key2{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key2{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key2{job=\"$source\"}",
     "legendFormat": "Scheduler"
    },
    { "expr": "NIC_Scheduler_Worker_key2", "legendFormat": "NIC+Scheduler+Worker" }
   ]
  },
  {
   "title": "Subscribers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\"}",
     "legendFormat": "Subscribers"
    }
   ]
  },
  { "title": "Aggregate Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Aggregate Rate -> $source ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "In: $source -> {{interface_name}}"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Control CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{source=\"$source\"}",
     "legendFormat": "Router: {{source}}"
    },
    {
     "expr": "platform_control_cpu_total_average_15{source=\"$source\"}",
     "legendFormat": "Router: {{source}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use{source=\"$source\"}/( system_memory_pools_summary_total_in_use{source=\"$source\"} + system_memory_pools_summary_available_memory{source=\"$source\"})*100",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$source\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Ingress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 10, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * 100) * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "In: $source -> {{interface_name}}"
      }
     ]
    },
    {
     "title": "Traffic Egress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 10, "x": 10, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "Out: $source -> {{interface_name}}"
      }
     ]
    }
   ]
  }
 ]
}