{
 "title": "cups-sunnyvale",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "port", "query": { "query": "label_values(port_port_id)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BNG CUPS",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c25/1|1/1/c28/1|1/1/c32/1|1/1/c33/1|1/1/c40/1|1/1/c41/1|1/1/c45/1|1/1/c46/1\"}*port_ethernet_oper_speed{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c25/1|1/1/c28/1|1/1/c32/1|1/1/c33/1|1/1/c40/1|1/1/c41/1|1/1/c45/1|1/1/c46/1\"})*100",
     "legendFormat": "fp5-access:in"
    },
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c25/1|1/1/c28/1|1/1/c32/1|1/1/c33/1|1/1/c40/1|1/1/c41/1|1/1/c45/1|1/1/c46/1\"}*port_ethernet_oper_speed{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c25/1|1/1/c28/1|1/1/c32/1|1/1/c33/1|1/1/c40/1|1/1/c41/1|1/1/c45/1|1/1/c46/1\"})*100",
     "legendFormat": "fp5-access:out"
    },
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"sr-1x-fp5:57400\", port_port_id=~\"1/1/c1/1|1/1/c4/1|1/1/c8/1|1/1/c9/1|1/1/c16/1|1/1/c17/1|1/1/c21/1|1/1/c24/1\"}*port_ethernet_oper_speed{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c1/1|1/1/c4/1|1/1/c8/1|1/1/c9/1|1/1/c16/1|1/1/c17/1|1/1/c21/1|1/1/c24/1\"})*100",
     "legendFormat": "fp5-inet:in"
    },
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"sr-1x-fp5:57400\", port_port_id=~\"1/1/c1/1|1/1/c4/1|1/1/c8/1|1/1/c9/1|1/1/c16/1|1/1/c17/1|1/1/c21/1|1/1/c24/1\"}*port_ethernet_oper_speed{source=\"sr-1x-fp5:57400\",port_port_id=~\"1/1/c1/1|1/1/c4/1|1/1/c8/1|1/1/c9/1|1/1/c16/1|1/1/c17/1|1/1/c21/1|1/1/c24/1\"})*100",
     "legendFormat": "fp5-inet:out"
    },
    {
     "expr": "sum(rate(port_ethernet_statistics_in_octets{source=\"sr-1-fp4:57400\",port_port_id=~\"1/1/2|1/1/3|1/1/4|1/1/5\"}[$__rate_interval]))*4",
     "legendFormat": "vsr-access:in"
    },
    {
     "expr": "sum(rate(port_ethernet_statistics_out_octets{source=\"sr-1-fp4:57400\",port_port_id=~\"1/1/2|1/1/3|1/1/4|1/1/5\"}[$__rate_interval]))*4",
     "legendFormat": "vsr-access:out"
    }
   ]
  },
  {
   "title": "SMF-1   ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_active_in_use)",
     "legendFormat": "IP addresses in use"
    },
    {
     "expr": "sum(mobile_gateway_pdn_sx_n4_signaling_pfcp_peer_statistics_resource_active_sessions)",
     "legendFormat": "PFCP sessions"
    }
   ]
  },
  {
   "title": "Traffic -> $source -> $port",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_ethernet_statistics_in_utilization{source=\"$source\", port_port_id=\"$port\"} * port_ethernet_oper_speed{port_port_id=\"$port\", source=\"$source\"}* 100",
     "legendFormat": "Ingress"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{source=\"$source\", port_port_id=\"$port\"} * port_ethernet_oper_speed{port_port_id=\"$port\", source=\"$source\"}* 100",
     "legendFormat": "Egress"
    },
    {
     "expr": "rate(port_ethernet_statistics_in_octets{source=\"$source\",port_port_id=\"$port\"}[$__rate_interval])*8",
     "legendFormat": "Ingress"
    },
    {
     "expr": "rate(port_ethernet_statistics_out_octets{source=\"$source\",port_port_id=\"$port\"}[$__rate_interval])*8",
     "legendFormat": "Egress"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 }, "format": "short", "valueName": "current" },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "UP session distribution (FP4)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"pfcp-sessions-ipoe\",source=\"sr-1-fp4:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    },
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\",source=\"sr-1-fp4:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    }
   ]
  },
  {
   "title": "# micronets in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets_in_use{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}",
     "legendFormat": "{{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% total in use (micronets)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}*100)/mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} ",
     "legendFormat": "--> {{address_pool_name}}"
    }
   ]
  },
  {
   "title": "UP session distribution (FP5)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"pfcp-sessions-ipoe\",source=\"sr-1x-fp5:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    },
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\",source=\"sr-1x-fp5:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    }
   ]
  },
  {
   "title": "# addresses in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}",
     "legendFormat": "In Use: {{address_pool_name}}"
    },
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_active_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} \n",
     "legendFormat": "Active: {{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% Addresses in use",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_active_in_use{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} \n*100)/mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_usable{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}\n\n",
     "legendFormat": "--> {{address_pool_name}}"
    }
   ]
  },
  {
   "title": "UP session distribution (FWA)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"pfcp-sessions-fwa\",source=\"vsr-upf:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    },
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\",source=\"vsr-upf:57400\"} ",
     "legendFormat": "{{sessions_counter}}"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 }, "format": "short", "valueName": "current" }
 ]
}