{
 "title": "cups",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wireline and Fixed Wireless Access",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(gnmic_sros_port_stats_up3_in_octets{source=\"up3\"}[10s])*8",
     "legendFormat": "up3:{{port_port_id}}:in"
    },
    {
     "expr": "irate(gnmic_sros_port_stats_up3_out_octets{source=\"up3\"}[10s])*8",
     "legendFormat": "up3:{{port_port_id}}:out"
    },
    {
     "expr": "irate(gnmic_sros_port_stats_tra_in_octets{source=\"tra\"}[10s])*8",
     "legendFormat": "tra:{{port_port_id}}:in"
    },
    {
     "expr": "irate(gnmic_sros_port_stats_tra_out_octets{source=\"tra\"}[10s])*8",
     "legendFormat": "tra:{{port_port_id}}:out"
    },
    {
     "expr": "irate(gnmic_sros_port_stats_up4_in_octets{source=\"up4\"}[10s])*8",
     "legendFormat": "up4:{{port_port_id}}:in"
    },
    {
     "expr": "irate(gnmic_sros_port_stats_up4_out_octets{source=\"up4\"}[10s])*8",
     "legendFormat": "up4:{{port_port_id}}:out"
    },
    {
     "expr": "rate(gnmic_sros_service_stats_tra_out_octets{source=\"tra\"}[30s])*8",
     "legendFormat": "tra:{{interface_interface_name}}:out"
    },
    {
     "expr": "rate(gnmic_sros_service_stats_tra_in_octets{source=\"tra\"}[30s])*8",
     "legendFormat": "tra:{{interface_interface_name}}:in"
    }
   ]
  },
  {
   "title": "SMF-1   (geo-redundancy)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total FWA 5G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total FWA 4G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total IPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total PPPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{session_name=\"Total NAT\"}",
     "legendFormat": "{{session_name}}"
    }
   ]
  },
  {
   "title": "SMF-2   (geo-redundancy)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total FWA 5G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total FWA 4G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total IPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total PPPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf2_number_of_sessions{session_name=\"Total NAT\"}",
     "legendFormat": "{{session_name}}"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 }, "format": "short", "valueName": "current" },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "UP3 session distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 .Total\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 FWA 5G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 FWA 4G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 IPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 PPPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP3 NAT\"}",
     "legendFormat": "{{session_name}}"
    }
   ]
  },
  {
   "title": "# micronets in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_odsa_v6_smf1_micro_nets_in_use",
     "legendFormat": "v6:{{address_pool_name}}"
    },
    {
     "expr": "gnmic_sros_odsa_v4_smf1_micro_nets_in_use",
     "legendFormat": "v4:{{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% total in use (micronets)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gnmic_sros_odsa_v6_smf1_micro_nets_in_use*100)/gnmic_sros_odsa_v6_smf1_micro_nets",
     "legendFormat": "-->"
    },
    {
     "expr": "(gnmic_sros_odsa_v4_smf1_micro_nets_in_use*100)/gnmic_sros_odsa_v4_smf1_micro_nets",
     "legendFormat": "-->"
    }
   ]
  },
  {
   "title": "UP4 session distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 .Total\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 FWA 5G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 FWA 4G\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 IPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 PPPoE\"}",
     "legendFormat": "{{session_name}}"
    },
    {
     "expr": "gnmic_sros_info_smf1_number_of_sessions{ session_name=\"UP4 NAT\"}",
     "legendFormat": "{{session_name}}"
    }
   ]
  },
  {
   "title": "# addresses in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_odsa_v6_smf1_ip_addresses_active_in_use",
     "legendFormat": "v6:{{address_pool_name}}"
    },
    {
     "expr": "gnmic_sros_odsa_v4_smf1_ip_addresses_active_in_use",
     "legendFormat": "v4:{{address_pool_name}}"
    },
    {
     "expr": "gnmic_sros_odsa_v4_smf1_ip_addresses_in_use",
     "legendFormat": "v4:{{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% total in use (addresses)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gnmic_sros_odsa_v6_smf1_ip_addresses_active_in_use*100)/gnmic_sros_odsa_v6_smf1_ip_addresses_usable",
     "legendFormat": "-->"
    },
    {
     "expr": "(gnmic_sros_odsa_v4_smf1_ip_addresses_active_in_use*100)/gnmic_sros_odsa_v4_smf1_ip_addresses_usable",
     "legendFormat": "-->"
    },
    {
     "expr": "(gnmic_sros_odsa_v4_smf1_ip_addresses_in_use*100)/gnmic_sros_odsa_v4_smf1_ip_addresses",
     "legendFormat": "-->"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "{job=\"syslog\"}"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 }, "format": "short", "valueName": "current" },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "# NAT flows (UP3)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnmic_sros_nat_flows_up3_value" }
   ]
  },
  {
   "title": "ESA health (UP3)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_esa_health_up3_hardware_status",
     "legendFormat": "hardware status"
    },
    {
     "expr": "gnmic_sros_esa_health_up3_power_supply_1_status",
     "legendFormat": "power supply 1"
    },
    {
     "expr": "gnmic_sros_esa_health_up3_power_supply_2_status",
     "legendFormat": "power supply 2"
    }
   ]
  },
  {
   "title": "ESA health (UP3)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_esa_health_up3_cpu_1_temperature",
     "legendFormat": "cpu "
    },
    {
     "expr": "gnmic_sros_esa_health_up3_power_supply_1_temp",
     "legendFormat": "power supply 1"
    },
    {
     "expr": "gnmic_sros_esa_health_up3_power_supply_2_temp",
     "legendFormat": "power supply 2"
    }
   ]
  },
  {
   "title": "# NAT flows (UP4)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnmic_sros_nat_flows_up4_value", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "ESA health (UP4)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_esa_health_up4_hardware_status",
     "legendFormat": "hardware status"
    },
    {
     "expr": "gnmic_sros_esa_health_up4_power_supply_1_status",
     "legendFormat": "power supply 1"
    },
    {
     "expr": "gnmic_sros_esa_health_up4_power_supply_2_status",
     "legendFormat": "power supply 2"
    }
   ]
  },
  {
   "title": "ESA health (UP4) ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_esa_health_up4_cpu_1_temperature",
     "legendFormat": "cpu temp"
    },
    {
     "expr": "gnmic_sros_esa_health_up4_power_supply_1_temp",
     "legendFormat": "power1 temp"
    },
    {
     "expr": "gnmic_sros_esa_health_up4_power_supply_2_temp",
     "legendFormat": "power2 temp"
    }
   ]
  }
 ]
}