{
 "title": "Development 1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Routes Default Instance, $source",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
     "legendFormat": "IPv4"
    },
    {
     "expr": "network_instance_route_table_ipv6_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
     "legendFormat": "IPv6"
    },
    {
     "expr": "router_bgp_statistics_routes_per_family_ipv4_remote_routes{source=\"$source\"}",
     "legendFormat": "IPv4"
    },
    {
     "expr": "router_bgp_statistics_routes_per_family_ipv6_remote_routes{source=\"$source\"}",
     "legendFormat": "IPv6"
    }
   ]
  },
  {
   "title": "BGP Peers: $source",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_bgp_convergence_family_up_peers{source=\"$source\",family_family_type=\"ipv6\"}",
     "legendFormat": "UP Peers"
    }
   ]
  },
  {
   "title": "BGP Route Advertisement $source",
   "type": "gauge",
   "description": "IXIA: 10k routes/s",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(router_bgp_neighbor_statistics_family_prefix_ipv4_sent{router_router_name=\"Base\",source=\"$source\"})\n\n",
     "legendFormat": "SENT: IPv4"
    },
    {
     "expr": "sum(router_bgp_neighbor_statistics_family_prefix_ipv6_sent{router_router_name=\"Base\",source=\"$source\"})",
     "legendFormat": "SENT: IPv6"
    }
   ]
  },
  { "title": "Routing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BGP Route Learning $source",
   "type": "timeseries",
   "description": "IXIA: 10k routes/s",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
     "legendFormat": "IPv4"
    },
    {
     "expr": "network_instance_route_table_ipv6_unicast_statistics_total_routes{source=\"$source\", network_instance_name=\"default\"}",
     "legendFormat": "IPv6"
    },
    {
     "expr": "router_bgp_statistics_routes_per_family_ipv4_remote_routes{source=\"$source\"}",
     "legendFormat": "IPv4"
    },
    {
     "expr": "router_bgp_statistics_routes_per_family_ipv6_remote_routes{source=\"$source\"}",
     "legendFormat": "IPv6"
    }
   ]
  },
  {
   "title": "BGP Route Advertisement $source",
   "type": "timeseries",
   "description": "IXIA: 10k routes/s",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_ipv4_sent{router_router_name=\"Base\",source=\"$source\"} \n\n",
     "legendFormat": "SENT: IPv4"
    },
    {
     "expr": "router_bgp_neighbor_statistics_family_prefix_ipv6_sent{router_router_name=\"Base\",source=\"$source\"} ",
     "legendFormat": "SENT: IPv6"
    }
   ]
  },
  {
   "title": "BGP Route Learning Rate $source",
   "type": "timeseries",
   "description": "IXIA: 10k routes/s",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "deriv(router_bgp_statistics_routes_per_family_ipv4_remote_routes{source=\"$source\"}[$__rate_interval])",
     "legendFormat": "Rate IPv4"
    },
    {
     "expr": "deriv(router_bgp_statistics_routes_per_family_ipv6_remote_routes{source=\"$source\"}[$__rate_interval])",
     "legendFormat": "Rate IPv6"
    }
   ]
  },
  {
   "title": "BGP Route Advertisement Rate $source",
   "type": "timeseries",
   "description": "IXIA: 10k routes/s",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "deriv(router_bgp_neighbor_statistics_family_prefix_ipv6_sent{neighbor_ip_address=\"2001:10:10:6::2\",router_router_name=\"Base\",source=\"$source\"}[$__rate_interval])",
     "legendFormat": "Rate Sent: IPv6"
    },
    {
     "expr": "deriv(router_bgp_neighbor_statistics_family_prefix_ipv4_sent{neighbor_ip_address=\"2001:10:10:6::2\",router_router_name=\"Base\",source=\"$source\"}[$__rate_interval])\n\n",
     "legendFormat": "Rate Sent: IPv4"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "VSR CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{source=\"$source\",subscription_name=\"sros-system-performance\"}",
     "legendFormat": "Router: {{source}}"
    },
    {
     "expr": "platform_control_cpu_total_average_15{source=\"$source\"}",
     "legendFormat": "Router: {{source}}"
    }
   ]
  },
  {
   "title": "CPU Process Utilization: $source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_bgp_capacity_usage{source=\"$source\"}",
     "legendFormat": "BGP Capacity Usage"
    },
    {
     "expr": "system_cpu_ip_stack_capacity_usage{source=\"$source\"}",
     "legendFormat": "IP Stack Capacity Usage"
    }
   ]
  },
  {
   "title": "vFP vCPUs -> $source",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NIC_key1{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key1{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key1{job=\"$source\"}",
     "legendFormat": "Scheduler"
    },
    { "expr": "NIC_Scheduler_Worker_key1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vFP Average Utilization -> $source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "NIC_key2{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key2{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key2{job=\"$source\"}",
     "legendFormat": "Scheduler"
    },
    { "expr": "NIC_Scheduler_Worker_key2", "legendFormat": "NIC+Scheduler+Worker" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use{source=\"$source\"}/( system_memory_pools_summary_total_in_use{source=\"$source\"} + system_memory_pools_summary_available_memory{source=\"$source\"})*100",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$source\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Ingress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * 100) * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "In: $source -> {{interface_name}}"
      }
     ]
    },
    {
     "title": "Traffic Egress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "Out: $source -> {{interface_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Aggregate Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Aggregate Rate -> $source ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "In: $source -> {{interface_name}}"
    }
   ]
  },
  {
   "title": "cVSR",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 14, "w": 4, "x": 8, "y": 44 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "UP0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "UP1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "UP2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/7|1/1/8|1/1/9\"}[$__rate_interval])*8)",
     "legendFormat": "UP3"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4|1/1/5|1/1/6\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN3"
    }
   ]
  },
  {
   "title": "MAC Table Instance: $network_instance, $source",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_instance_bridge_table_statistics_total_entries{network_instance_name=\"$network_instance\",source=\"$source\"}",
     "legendFormat": "MAC Entries"
    }
   ]
  }
 ]
}