{
 "title": "LAG Load Balancing",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   {
    "name": "port_id",
    "query": "([1-9]|1[0-2])/[1-4]/([1-9]|10)"
   },
   { "name": "func", "query": "rate, irate" },
   {
    "name": "interval",
    "query": "30s, 60s, 90s, 120s, 150s, 180s"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "$func(SROS_port_out_out_octets{source=~\"sros-[12].node.ipd.lab\", port_id=~\"$port_id\"}[$interval])*8",
     "legendFormat": "{{source}}:{{port_id}}:out"
    },
    {
     "expr": "$func(SROS_port_in_in_octets{source=~\"sros-[12].node.ipd.lab\", port_id=~\"$port_id\"}[$interval])*8",
     "legendFormat": "{{source}}:{{port_id}}:in"
    }
   ]
  },
  {
   "title": "sros-1_card-1_egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "$func(SROS_ipv4_filter_egress_offered_byte_offered_byte{source='sros-1.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Offered"
    },
    {
     "expr": "$func(SROS_ipv4_filter_egress_forwarded_byte_forwarded_byte{source='sros-1.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "$func(SROS_ipv4_filter_egress_dropped_byte_dropped_byte{source='sros-1.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "sros-2_card-1_ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "$func(SROS_ipv4_filter_ingress_offered_byte_offered_byte{source='sros-2.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Offered"
    },
    {
     "expr": "$func(SROS_ipv4_filter_ingress_forwarded_byte_forwarded_byte{source='sros-2.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "$func(SROS_ipv4_filter_ingress_dropped_byte_dropped_byte{source='sros-2.node.ipd.lab', slot_number='1'}[$interval])*8",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "sros-1_card-2_egress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "$func(SROS_ipv4_filter_egress_offered_byte_offered_byte{source='sros-1.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Offered"
    },
    {
     "expr": "$func(SROS_ipv4_filter_egress_forwarded_byte_forwarded_byte{source='sros-1.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "$func(SROS_ipv4_filter_egress_dropped_byte_dropped_byte{source='sros-1.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "sros-2_card-2_ingress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "$func(SROS_ipv4_filter_ingress_offered_byte_offered_byte{source='sros-2.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Offered"
    },
    {
     "expr": "$func(SROS_ipv4_filter_ingress_forwarded_byte_forwarded_byte{source='sros-2.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Forwarded"
    },
    {
     "expr": "$func(SROS_ipv4_filter_ingress_dropped_byte_dropped_byte{source='sros-2.node.ipd.lab', slot_number='2'}[$interval])*8",
     "legendFormat": "Dropped"
    }
   ]
  }
 ]
}