{
 "title": "mag-c",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "port", "query": { "query": "label_values(interface_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BNG CUPS",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 20, "w": 18, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"leaf1\", interface_name=~\"ethernet-1/25|ethernet-1/26\"})",
     "legendFormat": "leaf1-in"
    },
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"leaf2\", interface_name=~\"ethernet-1/25|ethernet-1/26\"})",
     "legendFormat": "leaf2-in"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"leaf2\", interface_name=~\"ethernet-1/25|ethernet-1/26\"})",
     "legendFormat": "leaf2-out"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"leaf1\", interface_name=~\"ethernet-1/25|ethernet-1/26\"})",
     "legendFormat": "leaf1-out"
    }
   ]
  },
  {
   "title": "Traffic -> $source -> $port",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_ethernet_statistics_in_utilization{source=\"$source\", port_port_id=\"$port\"} * port_ethernet_oper_speed{port_port_id=\"$port\", source=\"$source\"}* 100",
     "legendFormat": "Ingress"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{source=\"$source\", port_port_id=\"$port\"} * port_ethernet_oper_speed{port_port_id=\"$port\", source=\"$source\"}* 100",
     "legendFormat": "Egress"
    },
    {
     "expr": "rate(port_ethernet_statistics_in_octets{source=\"$source\",port_port_id=\"$port\"}[$__rate_interval])*8",
     "legendFormat": "Ingress"
    },
    {
     "expr": "rate(port_ethernet_statistics_out_octets{source=\"$source\",port_port_id=\"$port\"}[$__rate_interval])*8",
     "legendFormat": "Egress"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 }, "format": "short", "valueName": "current" },
  { "title": "Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "UP session distribution CVSR4",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"pfcp-sessions-ipoe\",source=\"cvsr4\"} ",
     "legendFormat": "{{sessions_counter}}"
    },
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\",source=\"cvsr4\"} ",
     "legendFormat": "{{sessions_counter}}"
    }
   ]
  },
  {
   "title": "# micronets in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets_in_use{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}",
     "legendFormat": "{{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% total in use (micronets)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}*100)/mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_micro_nets{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} ",
     "legendFormat": "--> {{address_pool_name}}"
    }
   ]
  },
  {
   "title": "UP session distribution CVSR2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"pfcp-sessions-ipoe\",source=\"cvsr2\"} ",
     "legendFormat": "{{sessions_counter}}"
    },
    {
     "expr": "subscriber_mgmt_statistics_sessions_current_value{sessions_counter=\"subscribers-total\",source=\"cvsr2\"} ",
     "legendFormat": "{{sessions_counter}}"
    }
   ]
  },
  {
   "title": "# addresses in use (ODSA)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}",
     "legendFormat": "In Use: {{address_pool_name}}"
    },
    {
     "expr": "mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_active_in_use{source=\"cp:57400\", subscription_name=\"bng-cp\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} \n",
     "legendFormat": "Active: {{address_pool_name}}"
    }
   ]
  },
  {
   "title": "% Addresses in use",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_active_in_use{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"} \n*100)/mobile_gateway_pdn_local_address_assignment_network_realm_address_pool_statistics_address_assignment_ip_addresses_usable{source=\"cp:57400\", network_realm_network_realm_name=~\"fwa-realm|fixed\"}\n\n",
     "legendFormat": "--> {{address_pool_name}}"
    }
   ]
  },
  { "type": "agenty-flowcharting-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 }, "format": "short", "valueName": "current" }
 ]
}