{
 "title": "NAT",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "source", "query": { "query": "label_values(source)" } },
   { "name": "interface", "query": { "query": "label_values(interface_name)" } },
   {
    "name": "network_instance",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "NAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vFP Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NIC_key3{job=\"$source\"}",
     "legendFormat": "NIC"
    },
    {
     "expr": "Worker_key3{job=\"$source\"}",
     "legendFormat": "Worker"
    },
    {
     "expr": "Scheduler_key3{job=\"$source\"}",
     "legendFormat": "Scheduler"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "isa_nat_group_mda_resources_flows_value",
     "legendFormat": "Flows"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic Ingress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * 100) * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "In: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "In: $source -> {{interface_name}}"
      }
     ]
    },
    {
     "title": "Traffic Egress -> $source ",
     "type": "stat",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"}",
       "legendFormat": "Out: $source -> {{interface_name}}"
      },
      {
       "expr": "irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8",
       "legendFormat": "Out: $source -> {{interface_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Aggregate Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Aggregate Rate -> $source ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(port_ethernet_statistics_out_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_out_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "Out: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(port_ethernet_statistics_in_utilization{source=\"$source\", interface_name=~\"$interface\"} * port_ethernet_oper_speed{interface_name=~\"$interface\", source=\"$source\"}* 100)",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(interface_traffic_rate_in_bps{source=\"$source\", interface_name=~\"$interface\"})",
     "legendFormat": "In: $source -> {{interface_name}}"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"$interface\"}[$__rate_interval])*8)",
     "legendFormat": "In: $source -> {{interface_name}}"
    }
   ]
  },
  {
   "title": "cVSR",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 14, "w": 9, "x": 8, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/1\"}[$__rate_interval])*8)",
     "legendFormat": "UP0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/1\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN0"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "UP1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/3\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN1"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "UP2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_in_octets{source=\"$source\", interface_name=~\"1/1/2\"}[$__rate_interval])*8)",
     "legendFormat": "UP3"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN2"
    },
    {
     "expr": "sum(irate(port_ethernet_statistics_out_octets{source=\"$source\", interface_name=~\"1/1/4\"}[$__rate_interval])*8)",
     "legendFormat": "DOWN3"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_summary_usage_cpu_usage{source=\"$source\",subscription_name=\"sros-system-performance\"}",
     "legendFormat": "Router: {{source}}"
    },
    {
     "expr": "platform_control_cpu_total_average_15{source=\"$source\"}",
     "legendFormat": "Router: {{source}}"
    }
   ]
  },
  {
   "title": "CPU Utilization: $source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_summary_busiest_core_utilization_cpu_usage{source=\"$source\"}",
     "legendFormat": "Busiest Core Utilization"
    },
    {
     "expr": "system_cpu_isa_cpu_usage{source=\"$source\"}",
     "legendFormat": "ISA CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_pools_summary_total_in_use{source=\"$source\"}/( system_memory_pools_summary_total_in_use{source=\"$source\"} + system_memory_pools_summary_available_memory{source=\"$source\"})*100",
     "legendFormat": "{{source}}"
    },
    {
     "expr": "platform_control_memory_utilization{source=\"$source\"}",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}