{
 "title": "PoC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "func", "query": "rate,irate" },
   { "name": "interval", "query": "30s,60s,90s,120s,180s" }
  ]
 },
 "panels": [
  { "title": "Weathermap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weathermap",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr-7s-fp5\"}[$interval])*8",
     "legendFormat": "sr5_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr-7s-fp5\"}[$interval])*8",
     "legendFormat": "sr5_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr14s-2\"}[$interval])*8",
     "legendFormat": "sr1_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr14s-2\"}[$interval])*8",
     "legendFormat": "sr1_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1sm-1\"}[$interval])*8",
     "legendFormat": "sr2_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1sm-1\"}[$interval])*8",
     "legendFormat": "sr2_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-48d-1\"}[$interval])*8",
     "legendFormat": "sr3_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-48d-1\"}[$interval])*8",
     "legendFormat": "sr3_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-30\"}[$interval])*8",
     "legendFormat": "sr4_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-30\"}[$interval])*8",
     "legendFormat": "sr4_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr14s-1\"}[$interval])*8",
     "legendFormat": "sr6_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr14s-1\"}[$interval])*8",
     "legendFormat": "sr6_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-26\"}[$interval])*8",
     "legendFormat": "sr7_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-26\"}[$interval])*8",
     "legendFormat": "sr7_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-27\"}[$interval])*8",
     "legendFormat": "sr8_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-27\"}[$interval])*8",
     "legendFormat": "sr8_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-28\"}[$interval])*8",
     "legendFormat": "sr9_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-28\"}[$interval])*8",
     "legendFormat": "sr9_{{port_port_id}}_in"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_out_octets{source=\"sr1-29\"}[$interval])*8",
     "legendFormat": "sr10_{{port_port_id}}_out"
    },
    {
     "expr": "$func(gnmic_sros_port_stats_in_octets{source=\"sr1-29\"}[$interval])*8",
     "legendFormat": "sr10_{{port_port_id}}_in"
    }
   ]
  },
  {
   "title": "Routing stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "ISIS Stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "SNMP__vRtrISISRoutes", "legendFormat": "{{agent_host}}_ISISRoutes" },
      { "expr": "SNMP__vRtrISISAltRoutes", "legendFormat": "{{agent_host}}_ISISAltRoutes" }
     ]
    },
    {
     "title": "BGP Stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "SNMP__vRtrBGPRoutes", "legendFormat": "{{agent_host}}_BGPRoutes" },
      { "expr": "SNMP__vRtrBGPAltRoutes", "legendFormat": "{{agent_host}}_BGPAltRoutes" },
      { "expr": "SNMP__vRtrStatBGPVpnRoutes", "legendFormat": "{{agent_host}}_BGPVpnRoutes" },
      { "expr": "SNMP__vRtrBGPVPNAltRoutes", "legendFormat": "{{agent_host}}_BGPVPNAltRoutes" }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "gnmic_sros_system_cpu_usage", "legendFormat": "{{source}}" }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      { "expr": "gnmic_sros_system_total_in_use", "legendFormat": "{{source}}" }
     ]
    },
    {
     "title": "Port Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "gnmic_sros_port_stats_in_utilization{port_port_id=~\"[1-6]/[1-2]/c([1-9]|[12][0-9]|3[0-6])/[1-9]|10\"}/100",
       "legendFormat": "{{source}}_{{port_port_id}}_in"
      },
      {
       "expr": "gnmic_sros_port_stats_out_utilization{port_port_id=~\"[1-6]/[1-2]/c([1-9]|[12][0-9]|3[0-6])/[1-9]|10\"}/-100",
       "legendFormat": "{{source}}_{{port_port_id}}_out"
      }
     ]
    },
    {
     "title": "Port Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "$func(gnmic_sros_port_stats_out_octets{port_port_id=~\"[1-6]/[1-2]/c([1-9]|[12][0-9]|3[0-6])/[1-9]|10\"}[$interval])*-8",
       "legendFormat": "{{source}}_{{port_port_id}}_out"
      },
      {
       "expr": "$func(gnmic_sros_port_stats_in_octets{port_port_id=~\"[1-6]/[1-2]/c([1-9]|[12][0-9]|3[0-6])/[1-9]|10\"}[$interval])*8",
       "legendFormat": "{{source}}_{{port_port_id}}_in"
      }
     ]
    }
   ]
  }
 ]
}