{
 "title": "SROS Topology/State",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Weathermap",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "SROS_port_state_port_state", "legendFormat": "{{port_id}}" }
   ]
  },
  {
   "title": "BGP peer states",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "SROS_bgp_state_session_state", "legendFormat": "{{ip_address}}" }
   ]
  },
  {
   "title": "Interface throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(SROS_port_in_in_octets[30s])*8",
     "legendFormat": "{{port_id}}_in"
    },
    {
     "expr": "-rate(SROS_port_out_out_octets[30s])*8",
     "legendFormat": "{{port_id}}_out"
    }
   ]
  },
  {
   "title": "BGP prefix stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "SROS_unicast_ipv4_bgp_active_routes",
     "legendFormat": "BGPv4"
    },
    {
     "expr": "SROS_unicast_ipv4_bgp_label_active_routes",
     "legendFormat": "BGPv4-LU"
    },
    {
     "expr": "SROS_unicast_ipv6_bgp_active_routes",
     "legendFormat": "BGPv6"
    },
    {
     "expr": "SROS_unicast_ipv6_bgp_label_active_routes",
     "legendFormat": "BGPv6-LU"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "SROS_cpu_usage_cpu_usage", "legendFormat": "CPU Load" }
   ]
  }
 ]
}