---
anchors:
  thresholds-operstate: &thresholds-operstate
    - color: "#FF3154" # red
      level: 0
    - color: "#4BDD33" # green
      level: 1
  thresholds-traffic: &thresholds-traffic
    - color: "#bec8d2" # grey
      level: 0
    - color: "#4BDD33" # green
      level: 199999999999
    - color: "#FFFF00" # yellow
      level: 500000000000
    - color: "#FF8000" # orange
      level: 1000000000000
    - color: "#FF3154" # red
      level: 5000000000000
  label-config: &label-config
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
      - valueMax: 1000000000000
        text:
      - valueMin: 199999999999
cellIdPreamble: cell-
cells:
  7750-1se:ixia:01:
    dataRef: 7750-1se:1/1/c1/1:out
    label: *label-config
  # 7750-1se:ixia:02:
  #   dataRef: 7750-1se:1/1/c1/2:out
  #   label: *label-config
  7750-1se:ixia:03:
    dataRef: 7750-1se:1/1/c5/1:in
    label: *label-config
  # 7750-1se:ixia:04:
  #   dataRef: 7750-1se:1/1/c5/2:out
  #   label: *label-config
  7750-2se:ixia:01:
    dataRef: 7750-2se:1/1/c25/1:in
    label: *label-config
  # 7750-2se:ixia:02:
  #   dataRef: 7750-2se:1/1/c25/2:out
  #   label: *label-config
  7750-2se:ixia:03:
    dataRef: 7750-2se:1/1/c31/1:in
    label: *label-config
  # 7750-2se:ixia:04:
  #   dataRef: 7750-2se:1/1/c31/2:out
  #   label: *label-config
  2se-test:
      dataRef: 7750-2se:1/1/c25/1:in
      label: *label-config
  2se-test2:
      dataRef: 7750-2se:1/1/c31/1:in
      label: *label-config
  flex-e:
      dataRef: 7750-2se:1/1/f11/1:out
      label: *label-config

