{
 "title": "7750 SR Power Optimization  2 cards",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Card 2 Power",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "card_mda_hardware_resource_wattage_current{card_slot_number=\"2\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Card 4 Power",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "card_mda_hardware_resource_wattage_current{card_slot_number=\"4\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #1"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #2"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #3"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #4"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #5"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #6"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 4 FP #1"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #2"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #3"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #4"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #5"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #6"
    }
   ]
  },
  {
   "title": "Chassis Power",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "system_power_management_total_wattage*0.001",
     "legendFormat": "Total Utilization"
    }
   ]
  },
  {
   "title": "SFM Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "sfm_hardware_resource_wattage_current",
     "legendFormat": "SFM {{sfm_sfm_slot}} Current"
    }
   ]
  },
  {
   "title": "Card 2 Power (W) vs Throughput (Tbps)",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "card_mda_hardware_resource_wattage_current{card_slot_number=\"2\"}*0.001",
     "legendFormat": "Power"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 0.00192",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Card 4 Power (W) vs Throughput (Tbps)",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "card_mda_hardware_resource_wattage_current{card_slot_number=\"4\"}*0.001",
     "legendFormat": "Power"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 0.00032",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Card Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "card_hardware_data_temperature", "legendFormat": "{{card_slot_number}}" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #1"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #2"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #3"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #4"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #5"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 2 FP #6"
    },
    {
     "expr": "port_ethernet_statistics_out_utilization{interface_name=\"4/1/c6/1\"} * 320000000",
     "legendFormat": "Card 4 FP #1"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #2"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #3"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #4"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #5"
    },
    {
     "expr": "card_installed_xiom_slots{card_slot_number=\"4\"}",
     "legendFormat": "Card 4 FP #6"
    }
   ]
  },
  {
   "title": "Fan Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "chassis_fan_hardware_resource_wattage_current",
     "legendFormat": "{{fan_fan_slot}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chassis_fan_speed", "legendFormat": "{{fan_fan_slot}}" }
   ]
  }
 ]
}