{
 "title": "SRX-H5-boxes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Network Topology",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{interface_name=~\"ethernet-1/1/1|ethernet-1/1/2|ethernet-1/31/1|ethernet-1/31/2|ethernet-1/2|ethernet-1/1\"}",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "7220 IXR H5-64D",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"h5-64d\"}",
     "legendFormat": "{{source}}:{{interface_name}}:state"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=~\"h5-64o\", interface_name=\"ethernet-1/1/1\"}!= 0 ",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "7220 IXR H5-64O",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "interface_oper_state{source=\"h5-64o\"}",
     "legendFormat": "{{source}}:{{interface_name}}:state"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=~\"h5-64o\", interface_name=\"ethernet-1/1/2\"}!= 0 ",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    }
   ]
  }
 ]
}