{
 "title": "SRX-SAR-1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "7705-SAR-1",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "port_oper_state{source=\"sar-1\"}",
     "legendFormat": "{{source}}:{{interface_name}}"
    }
   ]
  },
  {
   "title": "NAT: number of 1:1 addresses in-use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isa_nat_group_member_resources_large_scale_hosts_value",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NAT: number of flows",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "isa_nat_group_mda_resources_flows_value{source=\"sar-1\"}",
     "legendFormat": "Flows"
    }
   ]
  },
  {
   "title": "Throughput on port 1/1/c1/1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100*port_ethernet_statistics_out_utilization{source=\"sar-1\", interface_name=\"1/1/c1/1\"} * port_ethernet_oper_speed",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Throughput on port 1/1/c2/1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100*port_ethernet_statistics_in_utilization{source=\"sar-1\", interface_name=\"1/1/c2/1\"} * port_ethernet_oper_speed",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}