{
 "title": "Packet Trimming",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Queue", "label": "Queue", "query": { "query": "label_values(queue_queue_name)" } },
   {
    "name": "Interface",
    "label": "Interface",
    "query": {
     "query": "label_values({source=\"h6-64o\"},interface_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qos_packet_trimming_enable_packet_trimming",
     "legendFormat": "Packet Trimming     "
    }
   ]
  },
  {
   "title": "Total port rate at Bottleneck",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/3\"}+4000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Trimming",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 22, "w": 17, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/2\"}",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/1\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h5-64o\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "Non-Trimmed packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_transmitted_packets{queue_queue_name=\"unicast-3\"}[1m])",
     "legendFormat": "Transmit at Bottleneck"
    }
   ]
  },
  {
   "title": "Trimmed packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_trimmed_packets{queue_queue_name=\"unicast-6\"}[30s])",
     "legendFormat": "Transmit at Bottleneck"
    }
   ]
  },
  {
   "title": "Dropped packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_dropped_packets{source=\"h6-64o\",queue_queue_name=\"unicast-3\"}[30s])\n* on(source)\n(qos_packet_trimming_enable_packet_trimming{source=\"h6-64o\"} == bool 0)",
     "legendFormat": "Dropped at Bottleneck"
    }
   ]
  },
  {
   "title": "Multipath Reliable Connection (MRC)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Topology",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 23, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic throughput one link",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/25\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uplinks throughput",
   "type": "timeseries",
   "gridPos": { "h": 23, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/60/1\"}",
     "legendFormat": "ethernet-1/60/1"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/60/2\"}",
     "legendFormat": "ethernet-1/60/2"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/61/1\"}",
     "legendFormat": "ethernet-1/61/1"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/61/2\"}",
     "legendFormat": "ethernet-1/61/2"
    }
   ]
  },
  {
   "title": "Downlinks throughput",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/25\"}",
     "legendFormat": "{{interface_name}}"
    }
   ]
  }
 ]
}