{
 "title": "Packet Trimming",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Queue", "label": "Queue", "query": { "query": "label_values(queue_queue_name)" } },
   {
    "name": "Interface",
    "label": "Interface",
    "query": {
     "query": "label_values({source=\"h6-64o\"},interface_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qos_packet_trimming_enable_packet_trimming",
     "legendFormat": "Packet Trimming     "
    }
   ]
  },
  {
   "title": "Total port rate at Bottleneck",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\",interface_name=\"ethernet-1/3\"}+4000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packet Trimming",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 22, "w": 17, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/2\"}",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "interface_traffic_rate_in_bps{source=\"h6-64o\",interface_name=\"ethernet-1/1\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h6-64o\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_out_bps{source=\"h5-64o\"}+4000000000",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    }
   ]
  },
  {
   "title": "Non-Trimmed packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_transmitted_packets{queue_queue_name=\"unicast-3\"}[1m])",
     "legendFormat": "Transmit at Bottleneck"
    }
   ]
  },
  {
   "title": "Trimmed packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_trimmed_packets{queue_queue_name=\"unicast-6\"}[30s])",
     "legendFormat": "Transmit at Bottleneck"
    }
   ]
  },
  {
   "title": "Dropped packets (pps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(qos_interfaces_interface_output_queues_queue_queue_statistics_aggregate_statistics_dropped_packets{source=\"h6-64o\",queue_queue_name=\"unicast-3\"}[30s])\n* on(source)\n(qos_packet_trimming_enable_packet_trimming{source=\"h6-64o\"} == bool 0)",
     "legendFormat": "Dropped at Bottleneck"
    }
   ]
  },
  {
   "title": "statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Interface Queue depth ",
     "type": "bargauge",
     "description": "$Interface Queue depth 1 min average",
     "gridPos": { "h": 11, "w": 14, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qos_interfaces_interface_output_queues_queue_queue_depth_average_1{interface_interface_id=\"$Interface\"}",
       "legendFormat": "{{queue_queue_name}}"
      }
     ]
    }
   ]
  }
 ]
}